


on: # Remove # below for non default branches
   workflow_dispatch


jobs:
  pull-submodule:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: checkout own repository
        run: |
          git clone https://github.com/0VERL0DE/AutoHotkey.git tempdir
          ls
          cd tempdir
          ls
        
      
      
