


on: # Remove # below for non default branches
   workflow_dispatch


jobs:
  pull-submodule:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
       - name: Checkout this repository
         uses: actions/checkout@v4 
         with: 
             set-safe-directory: false
      
       - name: CheckOut Sitrep
         run: |
           ls

      
      
